# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: mkdocs.yml

mkdocs:
  configuration: mkdocs.yml

build:
  image: testing  # Specify a build image if needed, "latest" is also a common choice

python:
  version: 3.10
  install:
    - method: poetry
      path: .
