site_name: Simulacra Documentation

theme: material

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - MOdelling Market Dynamics: modelling_market_dynamics.md
  - Simulations:
      - Product Popularity: product_popularity.md
      - Stock Market: stock_market.md
      - Resource Fluctuations: resource_fluctuations.md
  - API Documentation: api.md
  - Contribute: contribute.md
  - Contact: contact.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true

document$.subscribe(({ body }) => { 
  renderMathInElement(body, {
    delimiters: [
      { left: "$$",  right: "$$",  display: true },
      { left: "$",   right: "$",   display: false },
      { left: "\\(", right: "\\)", display: false },
      { left: "\\[", right: "\\]", display: true }
    ],
  })
})